name: Test Docker Action

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hello World Action
        uses: ./ # action.yml in the root
        with: # This section passes input parameters to the Docker action.
          who-to-greet: "Mona the Octocat"
        env:
          MY_SECRET_API_KEY: ${{ secrets.MY_SECRET_API_KEY }} # Pass the repository secret
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Job-specific environment variables

        steps:
          - name: Print database URL
            run: echo "Database URL is $DATABASE_URL"
