name: Test Docker Action

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hello World Action
        uses: ./ # This assumes the action is in the same repository
        with:
          who-to-greet: "Mona the Octocat"
